"""Shared resource limits used before and after typed reconstruction."""

MAX_EVIDENCE_REFS = 256
MAX_EVIDENCE_INPUT_CHARS = 8_000_000
MAX_EVIDENCE_SOURCE_BLOCK_REFS = 20_000
MAX_EVIDENCE_SOURCE_BLOCK_CHARS = MAX_EVIDENCE_INPUT_CHARS
